### ISSUE TITLE
Frappe Gantt v0.3.0 not working, but older versions do

### ISSUE THREAD

**Issue by jonodjlee** [frappe/gantt#121]
I have been trying to include Frappe Gantt in one of my projects, but every time I imported the files for Gantt v0.3.0, it would result in a blank page. I went and downloaded Frappe Gantt v0.0.7, and it works perfectly... Could someone please tell me why the newer version just doesn't work or could someone show me the code for a project that has successfully gotten v0.3.0 to work for them. Thanks!

@netchampfaris

**Comment by Adioud** [comment]
Hi,
There was significant changes since the version showed in the demonstration page, and documentation is not up to date.
First you have to draw you Gantt on a div element, no more on a svg element as it's still mentioned in the documentation.
<div id="gantt"></div>
I hade the same problem than you, but I don't remember if there was other changes.
Good luck,
Adrien
