### ISSUE TITLE
Create baseline planned and actual date?

### ISSUE THREAD

**Issue by nbao** [frappe/gantt#304]
Hi,
How can i create base line to compare planned and actual date? I wanna show 2 lines planned timeline below actual date 

Thanks

**Comment by safwansamsudeen** [comment]
Good feature, will add.

**Comment by safwansamsudeen** [comment]
It turns out this already exists - set `show_expected_progress` to `true.`

**Comment by nbao** [comment]
Do you have an example, please?

**Comment by safwansamsudeen** [comment]
Download the demo and add the option, you will see.

**Comment by parthi2929** [comment]
@nbao I badly needed this feature, so tried to implement one. I forked, because it may not be as polished and well tested for this repo, but if you are interested to try, you can check out [here](https://github.com/parthi2929/gantt/releases/tag/v1.0.0).  It is quick hack sorts of thing for my needs, so may break here and there.  

![Image](https://github.com/user-attachments/assets/cfecc7e9-6377-4ebe-b0f0-f5cf3ae593a6)

**Comment by safwansamsudeen** [comment]
@parthi2929 did the `show_expected_progress` not work for you?

**Comment by parthi2929** [comment]
@safwansamsudeen theoretically, `show_expected_progress`'s purpose is different from why we need baseline.. we want to see, the initial planned timelines vs what actually we ended up, thus 2 bars representing them in single row would have been ideal.. not just, if actual task exceeded estimated time. Also I think `show_expected_progress` logic assumes linear progression (if 10 days planned, then 20% should be over in 2 days), which also may not be representative of how the task is progressing.. so we do not need that measure.. nevertheless I gave it a try , and its awaiting resolution in #512
