### ISSUE TITLE
why readonly option is not available on latest release 0.6.1

### ISSUE THREAD

**Issue by vetik32** [frappe/gantt#409]
it's present if I install

```bash
 npm install git+https://github.com/frappe/gantt.git
 ```
 
 ```js
 
 
const DEFAULT_OPTIONS = {
  ...
  readonly: false,
  ...
  }
  ```

**Comment by Alex4Codes** [comment]
+
readonly: false - not work 0.6.1

**Comment by KebabRonin** [comment]
I think it may be because there was no new release made to npm after the big updates in April. PR #393 introduced the readonly option, but the version wasn't increased.

The [npm version of frappe-gantt](https://www.npmjs.com/package/frappe-gantt?activeTab=versions) was last updated 2 years ago.

@netchampfaris, could you maybe look into this? Does the npm release need to be run manually? (if it was supposed to be automatic, maybe the last commit broke the github workflow?)

**Comment by safwansamsudeen** [comment]
Yep, we need to run the npm release. We will after fixing the bugs in the April release - probably by the end of this month!
