### ISSUE TITLE
Collapse bars and resize GANTT diagram

### ISSUE THREAD

**Issue by SebLeich** [frappe/gantt#42]
Hey there,

does someone know a possibility to collapse bars? I already used the custom-class but i don't know how to resize the diagram (hide the row of the bar) and hide the arrows.

CSS "hide"

`.hide {
    display: none;
}`

JS

`function hideTask(index){
    tasks[index].custom_class = "hide";
    gantt_chart.refresh(tasks);
}`

**Comment by netchampfaris** [comment]
I don't think this is easily doable using CSS. We might have to do this as a feature.

**Comment by jgorene** [comment]
Hello,
I started working on this feature because for a gantt view, it's fundamental, it seems.
Il y a aussi que "frappe-gantt" is really interesting according to use.
Otherwise, just with css ... I don't know to do that and I wonder if it's possible or easy indeed when most of the objects are nested from svg... but it would be perfect, of course!

Short answer, I use d3.js to create depths in the groups of bars according to the tasks but each one implement this with its own method because it's not so simple anyway 
For now I am still at the experimental stage with frappe-gantt ;)
It then allows to hide or show groups of dependent bars as seen on the gif ...
Still a lot to do anyway for me ;)

![frappe002](https://user-images.githubusercontent.com/16499959/36092136-9b470e70-0fe6-11e8-8261-94f579760da4.gif)

**Comment by netchampfaris** [comment]
@jgorene If you have a working version, why not open a PR?

**Comment by Anurag810** [comment]
@jgorene please open PR

**Comment by abhishekk2304** [comment]
@jgorene Are you still working on it or have some workable solution.
Please suggest how i can integrate D3 with frappe-gantt to have expand collapse feature. It would be very helpful if you share your thoughts.

**Comment by unnhao** [comment]
Wow，I think I need this, my project need to collapse gantt, I have no idea how to implement 😢

**Comment by arxheji** [comment]
@jgorene we need you :(

**Comment by jgorene** [comment]
Hello ! Sorry for the delay...
Although still open, this problem is old and frappe-gantt has also evolved a lot since then.

Anyway, I tried to review this without adding any other libraries... just in pure js.
Of course, this is to be adapted according to your needs and is probably perfectible but if it can help someone.

See working [codepen](https://codepen.io/jean2607/full/GRyRxBM)

**Comment by jgorene** [comment]
Finally I found a more elegant solution it seems...
Working [codepen](https://codepen.io/jean2607/full/YzYyVzE)

Although it seems possible, I haven't yet figured out how to add it to the library via a PR.
Feel free to comment or even improve the thing if you think it's an interesting idea.
At least for now...

**Comment by safwansamsudeen** [comment]
IDT this is a much requested feature - if it is, we can add.
