### ISSUE TITLE
dates a little off

### ISSUE THREAD

**Issue by bensialih** [frappe/gantt#48]
Hey guys,

Great work.
Been running some tests and it seems the dates seem a little off when being displayed graphically.
See attach
![screenshot from 2018-01-25 01 50 48](https://user-images.githubusercontent.com/14818716/35366706-9fded1d4-0172-11e8-8b3c-c34df3982f35.png)
ment

**Comment by coulson84** [comment]
Yeah, I have noticed this too. It is associated with daylight saving times I think. Does your locale do daylight saving time @bensialih ? For me the dates went wonky at the transition of daylight saving time when the date transitioned from over from daylight saving time the header at the top skipped a day 

![image](https://user-images.githubusercontent.com/1502429/35377920-e1da2e72-01a8-11e8-83a9-f73a6bd82db8.png)

so the task TestImport1 starts on 30th October in the above image but because of the bug in the header it (and all dates after it) show as starting a day early. 

Going to have a look at it today if I get the chance.

**Comment by netchampfaris** [comment]
@bensialih Hi, this should be fixed in the latest version.
