### ISSUE TITLE
NS_ERROR_FAILURE in firefox when gantt is invisible

### ISSUE THREAD

**Issue by Armarr** [frappe/gantt#82]
There is a known bug in firefox that causes a native code error when trying to call getBBox on an invisible element:
https://bugzilla.mozilla.org/show_bug.cgi?id=612118

The naive fix for this is quite simple, remove the "remove out-of-bound dates" section from /index.js.
However I'm note sure what this code does. Is it for performance? Is there a better solution?

**Comment by guushoekman** [comment]
Has anyone taken a look at this?

@Armarr have you found a solution?

**Comment by guushoekman** [comment]
Not sure if this was exactly your case @Armarr, but I kept getting the `NS_ERROR_FAILURE` error and resolved it by using [the javascript file](https://frappe.io/gantt/js/frappe-gantt.min.js) Frappe use on their demo page instead of [the one in the repo](https://github.com/frappe/gantt/blob/master/dist/frappe-gantt.js).

I don't know why this works. There is no version number in the files so I don't know which one is more recent. I essentially know nothing except that for now it also works in Firefox.

**Comment by Armarr** [comment]
@guushoekman
I think the demo uses an older version.
My "solution" was to just remove the xode section that causes the error. I don't know ehat it does but it doesn't seem to be super important..

**Comment by guushoekman** [comment]
OK great, thanks for the info!
